const POPULAR = [
    // { name: "Pastie", file: "../clean.css" },
    // { name: "----", file: "", dark: true },
    { name: "Grayscale", file: "grayscale.css" },
    { name: "Mono Blue", file: "mono-blue.css" },

    { name: "----", file: "", dark: true },
    { name: "Dark", file: "dark.css", dark: true },
    { name: "Gradient Dark", file: "gradient-dark.css", dark: true },
    { name: "Hybrid", file: "hybrid.css", dark: true },
    { name: "Ir Black", file: "ir-black.css", dark: true },
    { name: "Monokai Sublime", file: "monokai-sublime.css", dark: true },
    { name: "Night Owl", file: "night-owl.css", dark: true },
    { name: "Nord", file: "nord.css", dark: true },
    { name: "Railscasts", file: "railscasts.css", dark: true },
    { name: "Shades of Purple", file: "shades-of-purple.css", dark: true },
    { name: "Srcery", file: "srcery.css", dark: true },
    { name: "----", file: "", dark: true },

    { name: "Atom One (light)", file: "atom-one-light.css" },
    { name: "Docco", file: "docco.css" },
    { name: "Foundation", file: "foundation.css" },
    { name: "GitHub", file: "github-gist.css" },
    { name: "Gruvbox (light)", file: "gruvbox-light.css" },
    { name: "Solarized (light)", file: "solarized-light.css" },
    { name: "Understated", file: "default.css" },
    { name: "XCode (light)", file: "xcode.css" },
]

const THEMES = [
    // { name: "A11y Light", file: "a11y-light.css" },

    // { name: "A11y (dark)", file: "a11y-dark.css", dark: true },
    // { name: "Agate", file: "agate.css", dark: true },
    // { name: "Arduino", file: "arduino-light.css" },
    // // { name: "An Old Hope", file: "an-old-hope.css", dark: true },
    // { name: "Ascetic", file: "ascetic.css", dark: true },
    // { name: "Atom One (light)", file: "atom-one-light.css" },
    // { name: "Atom One (dark)", file: "atom-one-dark.css" },
    // // { name: "Atom One Reasonable (dark)", file: "atom-one-dark-reasonable.css" },
    // { name: "Darcula", file: "darcula.css" },
    // { name: "Foundation", file: "foundation.css" },
    // { name: "Github", file: "github.css" },
    // { name: "Github Gist", file: "github-gist.css" },
    // { name: "Gruvbox (light)", file: "gruvbox-light.css" },
    // { name: "Gruvbox (dark)", file: "gruvbox-dark.css", dark:true },
    // { name: "Kimbie (light)", file: "kimbie.light.css" },
    // { name: "Kimbie (dark)", file: "kimbie.dark.css", dark:true },
    // { name: "Hopscotch", file: "hopscotch.css" },
    // // { name: "Lightfair", file: "lightfair.css", dark: true },
    // { name: "Obsidian", file: "obsidian.css", dark: true },
    // { name: "Sunburst", file: "sunburst.css", dark: true },
    // // { name: "Tomorrow Night (eighties)", file: "tomorrow-night-eighties.css", dark: true },
    // { name: "VS 2015", file: "vs2015.css", dark: true },
    // { name: "Visual Studio", file: "vs.css", dark: true },
    // { name: "Zenburn", file: "zenburn.css", dark: true },

    {name: "a11y-dark.css", file: "a11y-dark.css" },
    {name: "a11y-light.css", file: "a11y-light.css" },
    {name: "agate.css", file: "agate.css" },
    {name: "an-old-hope.css", file: "an-old-hope.css" },
    {name: "androidstudio.css", file: "androidstudio.css" },
    {name: "arduino-light.css", file: "arduino-light.css" },
    {name: "arta.css", file: "arta.css" },
    {name: "ascetic.css", file: "ascetic.css" },
    {name: "atelier-cave-dark.css", file: "atelier-cave-dark.css" },
    {name: "atelier-cave-light.css", file: "atelier-cave-light.css" },
    {name: "atelier-dune-dark.css", file: "atelier-dune-dark.css" },
    {name: "atelier-dune-light.css", file: "atelier-dune-light.css" },
    {name: "atelier-estuary-dark.css", file: "atelier-estuary-dark.css" },
    {name: "atelier-estuary-light.css", file: "atelier-estuary-light.css" },
    {name: "atelier-forest-dark.css", file: "atelier-forest-dark.css" },
    {name: "atelier-forest-light.css", file: "atelier-forest-light.css" },
    {name: "atelier-heath-dark.css", file: "atelier-heath-dark.css" },
    {name: "atelier-heath-light.css", file: "atelier-heath-light.css" },
    {name: "atelier-lakeside-dark.css", file: "atelier-lakeside-dark.css" },
    {name: "atelier-lakeside-light.css", file: "atelier-lakeside-light.css" },
    {name: "atelier-plateau-dark.css", file: "atelier-plateau-dark.css" },
    {name: "atelier-plateau-light.css", file: "atelier-plateau-light.css" },
    {name: "atelier-savanna-dark.css", file: "atelier-savanna-dark.css" },
    {name: "atelier-savanna-light.css", file: "atelier-savanna-light.css" },
    {name: "atelier-seaside-dark.css", file: "atelier-seaside-dark.css" },
    {name: "atelier-seaside-light.css", file: "atelier-seaside-light.css" },
    {name: "atelier-sulphurpool-dark.css", file: "atelier-sulphurpool-dark.css" },
    {name: "atelier-sulphurpool-light.css", file: "atelier-sulphurpool-light.css" },
    {name: "atom-one-dark-reasonable.css", file: "atom-one-dark-reasonable.css" },
    {name: "atom-one-dark.css", file: "atom-one-dark.css" },
    {name: "atom-one-light.css", file: "atom-one-light.css" },
    {name: "brown-paper.css", file: "brown-paper.css" },
    {name: "brown-papersq.png", file: "brown-papersq.png" },
    {name: "codepen-embed.css", file: "codepen-embed.css" },
    {name: "color-brewer.css", file: "color-brewer.css" },
    {name: "darcula.css", file: "darcula.css" },
    {name: "dark.css", file: "dark.css" },
    {name: "darkula.css", file: "darkula.css" },
    {name: "default.css", file: "default.css" },
    {name: "docco.css", file: "docco.css" },
    {name: "dracula.css", file: "dracula.css" },
    {name: "far.css", file: "far.css" },
    {name: "foundation.css", file: "foundation.css" },
    {name: "github-gist.css", file: "github-gist.css" },
    {name: "github.css", file: "github.css" },
    {name: "gml.css", file: "gml.css" },
    {name: "googlecode.css", file: "googlecode.css" },
    {name: "grayscale.css", file: "grayscale.css" },
    {name: "gruvbox-dark.css", file: "gruvbox-dark.css" },
    {name: "gruvbox-light.css", file: "gruvbox-light.css" },
    {name: "hopscotch.css", file: "hopscotch.css" },
    {name: "hybrid.css", file: "hybrid.css" },
    {name: "idea.css", file: "idea.css" },
    {name: "ir-black.css", file: "ir-black.css" },
    {name: "isbl-editor-dark.css", file: "isbl-editor-dark.css" },
    {name: "isbl-editor-light.css", file: "isbl-editor-light.css" },
    {name: "kimbie.dark.css", file: "kimbie.dark.css" },
    {name: "kimbie.light.css", file: "kimbie.light.css" },
    {name: "lightfair.css", file: "lightfair.css" },
    {name: "magula.css", file: "magula.css" },
    {name: "mono-blue.css", file: "mono-blue.css" },
    {name: "monokai-sublime.css", file: "monokai-sublime.css" },
    {name: "monokai.css", file: "monokai.css" },
    {name: "night-owl.css", file: "night-owl.css" },
    {name: "nord.css", file: "nord.css" },
    {name: "obsidian.css", file: "obsidian.css" },
    {name: "ocean.css", file: "ocean.css" },
    {name: "paraiso-dark.css", file: "paraiso-dark.css" },
    {name: "paraiso-light.css", file: "paraiso-light.css" },
    {name: "pojoaque.css", file: "pojoaque.css" },
    {name: "pojoaque.jpg", file: "pojoaque.jpg" },
    {name: "purebasic.css", file: "purebasic.css" },
    {name: "qtcreator_dark.css", file: "qtcreator_dark.css" },
    {name: "qtcreator_light.css", file: "qtcreator_light.css" },
    {name: "railscasts.css", file: "railscasts.css" },
    {name: "rainbow.css", file: "rainbow.css" },
    {name: "routeros.css", file: "routeros.css" },
    {name: "school-book.css", file: "school-book.css" },
    {name: "school-book.png", file: "school-book.png" },
    {name: "shades-of-purple.css", file: "shades-of-purple.css" },
    {name: "solarized-dark.css", file: "solarized-dark.css" },
    {name: "solarized-light.css", file: "solarized-light.css" },
    {name: "sunburst.css", file: "sunburst.css" },
    {name: "tomorrow-night-blue.css", file: "tomorrow-night-blue.css" },
    {name: "tomorrow-night-bright.css", file: "tomorrow-night-bright.css" },
    {name: "tomorrow-night-eighties.css", file: "tomorrow-night-eighties.css" },
    {name: "tomorrow-night.css", file: "tomorrow-night.css" },
    {name: "tomorrow.css", file: "tomorrow.css" },
    {name: "vs.css", file: "vs.css" },
    {name: "vs2015.css", file: "vs2015.css" },
    {name: "xcode.css", file: "xcode.css" },
    {name: "xt256.css", file: "xt256.css" },
    {name: "zenburn.css", file: "zenburn.css" }
]




THEMES.default = "shades-of-purple.css"
POPULAR.default = "shades-of-purple.css"
// exports.THEMES = POPULAR.concat(THEMES)
exports.THEMES = POPULAR

